---
title: No Votes for Genocide
timezone: America/New_York
description: Until an arms embargo and a permanent ceasefire are in place, withold any votes for Democrats. From Uncommitted NJ.
url: novotesforgenocide.org
logo: "/assets/vote-uncommitted.jpg"
image:
  path: "/assets/vote-uncommitted.jpg"
  alt: "Uncommitted logo"
highlighter: rouge
markdown: kramdown
permalink: ":title"
plugins:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
exclude:
- README.md
- Gemfile*
imagesurl: "/assets/sample-ballots/"
thumbsurl: "/assets/sample-ballot-thumbs/"
